// thank you ChatGPT for this list :D
const ideas = [
    "Personalized mug",
    "Customized jewelry",
    "Gourmet chocolate set",
    "Outdoor adventure experience",
    "Subscription to a streaming service",
    "Cooking class",
    "Spa day",
    "Handmade crafts",
    "Book collection",
    "Board games",
    "Fitness tracker",
    "Virtual reality headset",
    "Weekend getaway",
    "Language learning course",
    "Concert tickets",
    "Plant or flower arrangement",
    "Wine tasting tour",
    "Art supplies",
    "Cookware set",
    "Tech gadgets",
    "Candle set",
    "Home decor",
    "Scented bath products",
    "Fitness equipment",
    "Music instrument",
    "Cookbook",
    "Fashion accessories",
    "Photography workshop",
    "Personalized calendar",
    "Home gardening kit",
    "Cooking appliances",
    "DIY project kit",
    "Sports equipment",
    "Streaming device",
    "Fancy stationery",
    "Board game collection",
    "Virtual cooking class",
    "Art workshop",
    "Wine and cheese tasting",
    "Fitness class pass",
    "Crafting materials",
    "Adventure park tickets",
    "Home spa kit",
    "Eco-friendly products",
    "Music concert experience",
    "Fitness app subscription",
    "Pet accessories",
    "Online course enrollment",
    "Board game night kit",
    "Gourmet coffee set",
    "Home theater system",
    "Novelty socks",
    "Cooking utensils",
    "Personalized photo album",
    "Gardening tools",
    "Concert merchandise",
    "Antique or vintage items",
    "Fitness apparel",
    "Virtual museum tour",
    "Aromatherapy diffuser",
    "Local food tour",
    "Science experiment kit",
    "Outdoor grill set",
    "Origami kit",
    "Bluetooth speaker",
    "DIY woodworking kit",
    "Collectible figurines",
    "Calligraphy set",
    "Sustainable fashion items",
    "Escape room experience",
    "Coffee table books",
    "Cooking class gift card",
    "Fitness subscription box",
    "Art print or painting",
    "Home improvement tools",
    "Online painting tutorial",
    "Whiskey tasting set",
    "Gardening workshop",
    "DIY electronics kit",
    "Cooking magazine subscription",
    "Virtual yoga retreat",
    "Custom portrait session",
    "Hiking gear",
    "Baking supplies",
    "Music streaming service subscription",
    "Gourmet spice set",
    "Personalized stationery",
    "Local brewery tour",
    "Artificial intelligence gadget",
    "Home workout equipment",
    "Online dance lessons",
    "Cocktail mixing kit",
    "Outdoor camping gear",
    "DIY soap-making kit",
    "Vintage record player",
    "Culinary tour",
    "Plant care workshop",
    "Classic literature collection",
    "Fitness challenge program",
    "Sustainable living starter kit",
    "Online meditation course",
    "Outdoor picnic set",
    "Knitting or crochet kit",
    "Virtual language exchange",
    "Local theater show tickets",
    "Aquarium or zoo membership",
    "Sculpture or pottery class",
    "DIY candle-making kit",
    "Photography book",
    "Bird-watching guide",
    "Board game expansion packs",
    "Digital art tablet",
    "Local farm-to-table dining experience",
    "Paint and sip event",
    "Gourmet dessert delivery",
    "Home office organization supplies",
    "Puzzle collection",
    "Online gardening workshop",
    "Rock climbing lesson",
    "Homemade jam or preserves",
    "Foreign language books",
    "Virtual reality game",
    "Exotic cooking ingredients",
    "Terrarium-building kit",
    "Online comedy show tickets",
    "Home cocktail bar set",
    "Fitness motivation book",
    "Local art gallery membership",
    "Outdoor photography excursion",
    "Wine and painting night",
    "Mindfulness meditation app subscription",
    "Custom-designed sneakers",
    "Bicycle tour",
    "Home beer brewing kit",
    "Local history walking tour",
    "Yoga retreat weekend",
    "Sewing machine",
    "DIY home renovation guide",
    "Cooking spice subscription",
    "Concert poster art print",
    "Indoor plant collection",
    "Home juicer or blender",
    "Online painting class",
    "Craft beer tasting kit",
    "Classic film collection",
    "Virtual astronomy workshop",
    "Gourmet olive oil set",
    "Custom board game",
    "Ethical fashion clothing",
    "Artificial plant arrangement",
    "Dance fitness class membership",
    "Coffee subscription service",
    "Historical fiction book series",
    "Nature photography guide",
    "DIY pottery kit",
    "Adventure travel book",
    "Local artisanal cheese selection",
    "Jewelry-making supplies",
    "Virtual cocktail mixing class",
    "Personalized music playlist",
    "Local outdoor sculpture park visit",
    "Herb garden kit",
    "Gourmet hot sauce set",
    "Origami instruction book",
    "Fitness workshop",
    "Online interior design course",
    "Local wine tasting event",
    "Calligraphy workshop",
    "Gourmet tea collection",
    "Home pizza oven",
    "Virtual museum art tour",
    "Dance performance tickets",
    "Botanical illustration kit",
    "Craft cocktail recipe book",
    "Outdoor survival gear",
    "Culinary masterclass",
    "Bicycle maintenance kit",
    "Photography equipment rental",
    "Sustainable kitchenware set",
    "Yoga and meditation retreat",
    "Beekeeping starter kit",
    "Virtual wildlife photography class",
    "Indoor rock climbing session",
    "Custom fragrance creation experience",
    "Local theater workshop",
    "Cooking demonstration event",
    "Personalized fitness plan",
    "Outdoor painting workshop",
    "Pottery wheel class",
    "Virtual gardening consultation",
    "Wine and chocolate pairing",
    "Home brewing workshop",
    "Historical walking tour",
    "DIY home spa day kit",
    "Nature journaling supplies",
    "Virtual home workout program",
    "Gourmet popcorn set",
    "Indoor gardening kit",
    "Art therapy session",
    "Wine and cheese picnic",
    "Outdoor photography workshop",
    "Ethical fashion accessories",
    "Cooking ingredient subscription",
    "Virtual dance party experience",
    "Local herbalism class",
    "Home fermentation kit",
    "Photography book collection",
    "Virtual fine art class",
    "Personalized workout app",
    "Gourmet chocolate and wine tasting",
    "Woodworking tools",
    "Historical documentary collection",
    "Gardening gloves and tools",
    "Online painting workshop",
    "Local craft brewery tour",
    "Yoga and mindfulness app subscription",
    "Baking and pastry cookbook",
    "Gourmet coffee grinder",
    "Outdoor painting supplies",
    "DIY natural skincare kit",
    "Virtual cooking competition",
    "Local farm visit and cooking class",
    "Wine and painting workshop",
    "Home hydroponics kit",
    "Bicycle tour guidebook",
    "Fitness retreat weekend",
    "Art history lecture series",
    "Virtual home organization workshop",
    "Sustainable fashion workshop",
    "Indoor plant care guide",
    "Jewelry-making workshop",
    "Virtual cocktail party",
    "Nature photography workshop",
    "Home beer-making workshop",
    "Personalized meditation app",
    "Local theater performance tickets",
    "Gourmet cocktail mixers set",
    "Ethical fashion shopping spree",
    "Cooking gadget collection",
    "Virtual painting party",
    "Outdoor adventure book",
    "Online wellness retreat",
    "Gourmet chocolate-making class",
    "Indoor gardening workshop",
    "Craft beer selection",
    "Fitness equipment rental",
    "Botanical art supplies",
    "Virtual wildlife conservation seminar",
    "Local wine and cheese event",
    "Home barista kit",
    "Historical fiction book collection",
    "DIY home renovation workshop",
    "Cooking workshop with a chef",
    "Sustainable kitchen garden kit",
    "Yoga and meditation app subscription",
    "Outdoor sculpture park visit",
    "Gourmet cooking ingredient set",
    "Art therapy coloring books",
    "Local photography tour",
    "Virtual outdoor painting session",
    "Bicycle maintenance workshop",
    "Photography equipment loaner",
    "Ethical fashion wardrobe makeover",
    "Home fermentation workshop",
    "Virtual cooking class series",
    "Local historical site visit",
    "Wine and cheese tasting evening",
    "Home gardening essentials kit",
    "Indoor plant care workshop",
    "Sustainable fashion book",
    "Jewelry-making materials",
    "Virtual mixology class",
    "Nature photography retreat",
    "Home beer-brewing kit",
    "Personalized mindfulness app",
    "Local theater play tickets",
    "Gourmet cocktail ingredients",
    "Ethical fashion styling session",
    "Cooking utensil set",
    "Virtual art history lecture",
    "Outdoor adventure documentary collection",
    "Online gardening course",
    "Gourmet coffee subscription",
    "Indoor plant collection",
    "Art therapy workshop",
    "Wine and cheese pairing evening",
    "Home brewing supplies",
    "Photography equipment workshop",
    "Sustainable kitchenware workshop",
    "Yoga retreat package",
    "Outdoor painting class",
    "Local wildlife observation tour",
    "DIY skincare ingredients",
    "Virtual dance fitness class",
    "Ethical fashion shopping guide",
    "Cooking ingredient variety pack",
    "Virtual painting workshop",
    "Historical biography collection",
    "Online sustainable living seminar",
    "Gourmet chocolate-making workshop",
    "Indoor plant care class",
    "Craft beer brewing kit",
    "Fitness equipment demonstration",
    "Botanical art workshop",
    "Local bird-watching tour",
    "Home brewing workshop",
    "Photography technique seminar",
    "Ethical fashion brand spotlight",
    "Cooking tool set",
    "Virtual art workshop",
    "Outdoor adventure travel guide",
    "Online photography course",
    "Gourmet coffee tasting set",
    "Indoor plant care guidebook",
    "Art therapy painting kit",
    "Wine and cheese tasting class",
    "Home fermentation materials",
    "Photography equipment rental",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese tasting evening",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese tasting evening",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial",
    "Virtual art workshop series",
    "Outdoor adventure documentary collection",
    "Online gardening seminar",
    "Gourmet coffee subscription service",
    "Indoor plant care book",
    "Art therapy session package",
    "Wine and cheese pairing workshop",
    "Home fermentation workshop",
    "Photography equipment rental program",
    "Sustainable kitchenware workshop",
    "Yoga retreat weekend package",
    "Local theater performance tickets",
    "Gourmet cocktail mixers assortment",
    "Ethical fashion wardrobe consultation",
    "Cooking gadget collection",
    "Virtual art history lecture series",
    "Outdoor adventure travel guidebook",
    "Online photography course package",
    "Gourmet coffee tasting selection",
    "Indoor plant care guidebook",
    "Art therapy painting supplies",
    "Wine and cheese appreciation class",
    "Home brewing supplies kit",
    "Photography equipment workshop",
    "Sustainable kitchenware selection",
    "Yoga and meditation retreat package",
    "Local theater workshop series",
    "Gourmet cocktail recipe book",
    "Ethical fashion accessories collection",
    "Cooking technique masterclass",
    "Virtual art history seminar",
    "Outdoor adventure gear",
    "Online gardening workshop",
    "Gourmet coffee blend collection",
    "Indoor plant care manual",
    "Art therapy coloring supplies",
    "Wine and cheese appreciation class",
    "Home brewing ingredients",
    "Photography equipment loan program",
    "Sustainable kitchenware kit",
    "Yoga and mindfulness app subscription package",
    "Local art gallery membership",
    "Gourmet cocktail ingredients set",
    "Ethical fashion shopping experience",
    "Cooking technique tutorial"
];


const randomGen = document.getElementById("randomGenButton");
const ideaDisplay = document.getElementById("ideaDisplay");

function showRandomGiftIdea() {
    const randomIndex = Math.floor(Math.random() * ideas.length);
    const randomIdea = ideas[randomIndex];
    ideaDisplay.textContent = randomIdea;
}

randomGen.addEventListener("click",showRandomGiftIdea);